# Generated by Django 2.0 on 2020-06-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todopoints',
            name='todolist_id',
        ),
        migrations.DeleteModel(
            name='TodoPoints',
        ),
    ]
