# Generated by Django 2.0 on 2020-06-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200626_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todopoint', models.CharField(max_length=500)),
                ('todolist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.TodoList')),
            ],
            options={
                'db_table': 'todopoints',
            },
        ),
    ]
